name: data_mining
channels: 
  - conda-forge
dependencies:
  - python=3.6
  - jupyter
  - scikit-learn
  - pandas
  - seaborn
  - dask
  - matplotlib 
  - dask-ml
  - keras==2.1.6 
  - tensorboard==1.9.0
  - tensorflow==1.9.0
