name: ioosaccess
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - conda-forge::numpy
  - bokeh
  - cartopy
  - erddapy
  - folium
  - geolinks
  - geopandas
  - ioos_tools
  - iris>=1.12
  - jupyter
  - jupyter_contrib_nbextensions
  - matplotlib
  - nb_conda_kernels
  - netcdf4
  - owslib
  - palettable
  - pandas
  - pyoos
  - rasterio
  - requests
  - rtree
  - scipy
  - xarray
  - xlrd
  